apiVersion: apps/v1
kind: Deployment
metadata:
  name: joel-trisha-web-page
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joel-trisha-web-page
  template:
    metadata:
      labels:
        app: joel-trisha-web-page
    spec:
      containers:
      - name: joel-trisha-web-page
        image: babayagaaws/joel-trisha-web-page:latest
        ports:
        - containerPort: 8080