apiVersion: apps/v1
kind: Deployment
metadata:
  name: joel-trisha-web-page
  namespace: babayagaaws-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joel-trisha-web-page
  template:
    metadata:
      labels:
        app: joel-trisha-web-page
    spec:
      containers:
      - name: web-app
        image: babayagaaws/joel-trisha-web-page:latest  # Updated image
        ports:
        - containerPort: 8080
        imagePullPolicy: Always  # Force Kubernetes to pull the latest image