apiVersion: apps/v1
kind: Deployment
metadata:
  name: romantic-game
  namespace: babayagaaws-dev
  labels:
    app: romantic-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: romantic-game
  template:
    metadata:
      labels:
        app: romantic-game
    spec:
      securityContext:
        runAsUser: 0  # Run as root
      containers:
      - name: romantic-game
        image: babayagaaws/romantic-game
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: romantic-game-nginx
