apiVersion: v1
kind: Service
metadata:
  name: joel-trisha-web-page-service
  namespace: babayagaaws-dev
spec:
  selector:
    app: joel-trisha-web-page
  ports:
    - port: 8080        # Cluster-internal port (accessible via other pods)
      targetPort: 8080  # Pod port (where your app runs)
      nodePort: 30080   # External port (must be 30000-32767)
      protocol: TCP
      name: http
  type: NodePort