apiVersion: v1
kind: Service
metadata:
  name: romantic-game
  namespace: babayagaaws-dev
  labels:
    app: romantic-game
spec:
  selector:
    app: romantic-game
  ports:
  - protocol: TCP
    port: 80       # External port (used by the Service)
    targetPort: 80  # Internal port (used by the container, updated to 80)
  type: NodePort