apiVersion: v1
kind: Service
metadata:
  name: joel-trisha-web-page-service
  namespace: babayagaaws-dev
spec:
  selector:
    app: joel-trisha-web-page
  ports:
    - protocol: TCP
      port: 8080  # Port exposed by the service
      targetPort: 8080  # Port exposed by the container
  type: NodePort  # Exposes the service on a port on each node