apiVersion: v1
kind: Service
metadata:
  name: romantic-game
  namespace: babayagaaws-dev
  labels:
    app: romantic-game
spec:
  selector:
    app: romantic-game
  ports:
  - protocol: TCP
    port: 80       # External port (used by the Service)
    targetPort: 8080  # Internal port (used by the container)
  type: NodePort
  