apiVersion: v1
kind: Service
metadata:
  name: joel-trisha-web-page-service
  namespace: babayagaaws-dev
spec:
  type: ClusterIP  # Default type (internal traffic only)
  selector:
    app: joel-trisha-web-page
  ports:
    - port: 8080       # Cluster-internal port (other pods use this)
      targetPort: 8080 # Pod port (where your app runs)
      protocol: TCP
      name: http